language: ruby
dist: trusty
sudo: false
cache:
  bundler: true
rvm:
  - 2.5.5
env:
  matrix:
    - ALCHEMY_BRANCH=4.4-stable
    - ALCHEMY_BRANCH=4.5-stable
    - ALCHEMY_BRANCH=4.6-stable
    - ALCHEMY_BRANCH=master
    - SOLIDUS_BRANCH=v2.8
    - SOLIDUS_BRANCH=v2.9
    - SOLIDUS_BRANCH=v2.10
    - SOLIDUS_BRANCH=master
matrix:
  fast_finish: true
  allow_failures:
    - env: ALCHEMY_BRANCH=master
    - env: SOLIDUS_BRANCH=master
script: bundle exec rake
